export const palette = {
  yellow: '#FFC629',
  yellowDark: '#E6B020',
  cream: '#FFF8E7',
  creamDark: '#1A1610',
  black: '#0A0A0A',
  white: '#FFFFFF',
  gray100: '#F4F4F5',
  gray200: '#E4E4E7',
  gray400: '#A1A1AA',
  gray500: '#71717A',
  gray600: '#52525B',
  pinkAccent: '#FF4D8D',
  mint: '#7AE3C3',
  sky: '#7CB8FF',
  success: '#22C55E',
} as const;

export type ColorScheme = 'light' | 'dark';

export const colors = {
  light: {
    background: palette.cream,
    surface: palette.white,
    surfaceElevated: palette.white,
    text: palette.black,
    textSecondary: palette.gray600,
    muted: palette.gray500,
    border: palette.gray200,
    primary: palette.yellow,
    primaryForeground: palette.black,
    card: palette.white,
    overlay: 'rgba(10, 10, 10, 0.45)',
    tabBar: palette.white,
    tabIcon: palette.gray500,
    tabIconActive: palette.black,
    urgent: palette.yellowDark,
    accent: palette.pinkAccent,
  },
  dark: {
    background: palette.creamDark,
    surface: '#24211C',
    surfaceElevated: '#2E2A24',
    text: palette.white,
    textSecondary: palette.gray200,
    muted: palette.gray400,
    border: '#3F3A32',
    primary: palette.yellow,
    primaryForeground: palette.black,
    card: '#24211C',
    overlay: 'rgba(0, 0, 0, 0.55)',
    tabBar: '#1E1B17',
    tabIcon: palette.gray400,
    tabIconActive: palette.yellow,
    urgent: palette.yellow,
    accent: palette.pinkAccent,
  },
} as const;
